<h1>Lista de Estatística<h1>

# Exercício 1:

<p> 
Classifique as variáveis em: qualitativa (nominal ou ordinal), 
quantitativa (discreta ou contínua):

a) Tipo de vitamina (A, B1, B2, B6, B12): Qualitativa -> nominal 

b) Classificação de uma lesão (fatal; severa; moderada; pequena): Qualitativa -> ordinakl

c) Número de nascidos em certo hospital em jun/201:  Quantitativa-> discreta

d) Concentração de flúor na água - Quantitativa -> Continua

</p>

# Exercício 2

<p>
    a) Tendo em vista essa pesquisa, construa uma distribuição de frequência 
    sem intervalos de classe
</p>

In [36]:
import pandas as pd
import os
from collections import Counter

In [37]:
dados_bruto = [
    2, 3, 4, 4, 5, 3, 4,
    5, 6, 5, 3, 1, 5, 5,
    1, 3, 4, 5, 5, 5, 3,
    2, 2, 5, 4, 4, 2, 3,
    5, 4, 5, 4, 2, 4, 9,
]

In [38]:
len(dados_bruto)

35

In [39]:
contagem = Counter(dados_bruto)
print(dict(contagem))

{2: 5, 3: 6, 4: 9, 5: 11, 6: 1, 1: 2, 9: 1}

In [40]:
df_dados = pd.DataFrame(contagem.items(), columns=["Número", "Frequência"])
df_dados

   Número  Frequência
0       2           5
1       3           6
2       4           9
3       5          11
4       6           1
5       1           2
6       9           1

In [41]:
df_dados["Relativa"] = (df_dados["Frequência"] / len(dados_bruto)) * 100

df_dados["Relativa"] = df_dados["Relativa"].round(2)

print(df_dados)

   Número  Frequência  Relativa
0       2           5     14.29
1       3           6     17.14
2       4           9     25.71
3       5          11     31.43
4       6           1      2.86
5       1           2      5.71
6       9           1      2.86

In [42]:
df_dados["Frequência Acumulada"] = df_dados["Frequência"].cumsum()
df_dados

   Número  Frequência  Relativa  Frequência Acumulada
0       2           5     14.29                     5
1       3           6     17.14                    11
2       4           9     25.71                    20
3       5          11     31.43                    31
4       6           1      2.86                    32
5       1           2      5.71                    34
6       9           1      2.86                    35

<p>
a) Tendo em vista essa pesquisa, construa uma distribuição de frequência 
sem intervalos de classe


</p>

In [43]:
df_dados["Acumulada Relativa"] = (df_dados["Frequência Acumulada"] / len(dados_bruto)) * 100

df_dados["Acumulada Relativa"] = df_dados["Acumulada Relativa"].round(2)

df_dados

   Número  Frequência  Relativa  Frequência Acumulada  Acumulada Relativa
0       2           5     14.29                     5               14.29
1       3           6     17.14                    11               31.43
2       4           9     25.71                    20               57.14
3       5          11     31.43                    31               88.57
4       6           1      2.86                    32               91.43
5       1           2      5.71                    34               97.14
6       9           1      2.86                    35              100.00

---------------------------------------------------------

In [44]:

valor_maximo = max(dados_bruto)
print(valor_maximo)

valor_minimo = min(dados_bruto)
print(valor_minimo)

amplitude_total = valor_maximo - valor_minimo
amplitude_total

9
1

8

In [45]:
len(dados_bruto)

35

In [46]:
import math
k = (1 + 3.3 * math.log10(len(dados_bruto)))
numero_de_classes = round(k)
numero_de_classes

6

In [47]:
amplitude_total

8

In [48]:
amplitude_do_intervalo = round( amplitude_total / numero_de_classes)
amplitude_do_intervalo

1

In [49]:

bins = [valor_minimo + i*amplitude_do_intervalo for i in range(numero_de_classes+1)]
bins

[1, 2, 3, 4, 5, 6, 7]

In [50]:
classes = pd.cut(dados_bruto, bins=bins, right=True, include_lowest=True)
classes

[(0.999, 2.0], (2.0, 3.0], (3.0, 4.0], (3.0, 4.0], (4.0, 5.0], ..., (4.0, 5.0], (3.0, 4.0], (0.999, 2.0], (3.0, 4.0], NaN]
Length: 35
Categories (6, interval[float64, right]): [(0.999, 2.0] < (2.0, 3.0] < (3.0, 4.0] < (4.0, 5.0] < (5.0, 6.0] < (6.0, 7.0]]

In [51]:
frequencia_intervalos = classes.value_counts().sort_index()
frequencia_intervalos

(0.999, 2.0]     7
(2.0, 3.0]       6
(3.0, 4.0]       9
(4.0, 5.0]      11
(5.0, 6.0]       1
(6.0, 7.0]       0
Name: count, dtype: int64

In [52]:

# Montar DataFrame
df_frequencia_intervalo = pd.DataFrame({
    "Intervalo": frequencia_intervalos.index.astype(str),
    "Frequência": frequencia_intervalos.values
})

In [53]:
df_frequencia_intervalo["Relativa"] = (df_frequencia_intervalo["Frequência"] / len(dados_bruto) * 100).round(2)

In [54]:
df_frequencia_intervalo["Acumulada"] = df_frequencia_intervalo["Frequência"].cumsum()

In [55]:
df_frequencia_intervalo["Acumulada Relativa"] = df_frequencia_intervalo["Relativa"].cumsum().round(2)

In [56]:
df_frequencia_intervalo
#deu quebrado

      Intervalo  Frequência  Relativa  Acumulada  Acumulada Relativa
0  (0.999, 2.0]           7     20.00          7               20.00
1    (2.0, 3.0]           6     17.14         13               37.14
2    (3.0, 4.0]           9     25.71         22               62.85
3    (4.0, 5.0]          11     31.43         33               94.28
4    (5.0, 6.0]           1      2.86         34               97.14
5    (6.0, 7.0]           0      0.00         34               97.14

# Exercício 3

In [57]:

dados = {
    "Tempo (h)": ["0-4", "4-8", "8-12", "12-16", "16-20"],
    "Nº de pacientes": [8, 15, 24, 20, 13]
}

# Criando DataFrame
df_pacientes = pd.DataFrame(dados)

df_pacientes

  Tempo (h)  Nº de pacientes
0       0-4                8
1       4-8               15
2      8-12               24
3     12-16               20
4     16-20               13

In [58]:
df_pacientes["Relativa"] = (df_pacientes["Nº de pacientes"] / len(dados) * 100).round(2)

In [59]:
df_pacientes["Acumulada"] = df_pacientes["Nº de pacientes"].cumsum()

In [60]:
df_pacientes["Acumulada Relativa"] = df_pacientes["Relativa"].cumsum().round(2)
df_pacientes

  Tempo (h)  Nº de pacientes  Relativa  Acumulada  Acumulada Relativa
0       0-4                8     400.0          8               400.0
1       4-8               15     750.0         23              1150.0
2      8-12               24    1200.0         47              2350.0
3     12-16               20    1000.0         67              3350.0
4     16-20               13     650.0         80              4000.0

In [61]:
limites = [list(map(int, intervalos.split("-"))) for intervalos in df_pacientes["Tempo (h)"]]

limite_inferior = [l[0] for l in limites]
print(limite_inferior)
limite_superior = [l[1] for l in limites]
print(limite_superior)

[0, 4, 8, 12, 16]
[4, 8, 12, 16, 20]

In [62]:
df_pacientes["Ponto Médio"] = [(inferior + superior)/2 for inferior, superior in zip(limite_inferior, limite_superior)]
df_pacientes

,Tempo (h),Nº de pacientes,Relativa,Acumulada,Acumulada Relativa,Ponto Médio
0,0-4,8,400.0,8,400.0,2.0
1,4-8,15,750.0,23,1150.0,6.0
2,8-12,24,1200.0,47,2350.0,10.0
3,12-16,20,1000.0,67,3350.0,14.0
4,16-20,13,650.0,80,4000.0,18.0

<p>d) Interpretação da frequência relativa da 3ª classe<p>

In [63]:
total_pacientes = df_pacientes["Nº de pacientes"].sum()

In [64]:
df_pacientes["Nº de pacientes"][2]

np.int64(24)

In [65]:
frequencia_relativa_classe = df_pacientes["Nº de pacientes"][2] / total_pacientes *100
int(frequencia_relativa_classe)

30

In [66]:
print(f"{frequencia_relativa_classe}% dos pacientes dormiram entre {df_pacientes["Tempo (h)"][2]} horas.")

30.0% dos pacientes dormiram entre 8-12 horas.

e) Qual o percentual de pacientes que dormiram menos de 12h?

In [67]:
percent_menos_12h = df_pacientes[df_pacientes["Ponto Médio"] < 12]["Nº de pacientes"].sum() / total_pacientes * 100
percent_menos_12h

np.float64(58.75)

In [68]:
print(f"Percentual de pacientes que dormiram menos de 12h: {percent_menos_12h:.2f}%")

Percentual de pacientes que dormiram menos de 12h: 58.75%